"""Synthetic long coding context generator and KV cache simulation."""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np

from creation.memory.features import TokenRecord
from creation.memory.oracle import build_token_records


SAMPLE_FILES = [
    '''# utils/helpers.py
import os
from typing import List, Optional

def normalize_path(p: str) -> str:
    """Collapse redundant slashes."""
    return os.path.normpath(p)

def read_chunks(path: str, size: int = 4096) -> List[bytes]:
    chunks = []
    with open(path, "rb") as f:
        while True:
            block = f.read(size)
            if not block:
                break
            chunks.append(block)
    return chunks
''',
    '''# api/server.py
from fastapi import FastAPI, HTTPException
from models.user import User
from cache import kv_store

app = FastAPI()

@app.get("/users/{user_id}")
async def get_user(user_id: int) -> User:
    cached = kv_store.get(f"user:{user_id}")
    if cached:
        return cached
    user = await User.fetch(user_id)
    if user is None:
        raise HTTPException(status_code=404)
    kv_store.set(f"user:{user_id}", user, ttl=300)
    return user
''',
    '''# models/user.py
from dataclasses import dataclass
from database import db

@dataclass
class User:
    id: int
    name: str
    email: str

    @classmethod
    async def fetch(cls, user_id: int) -> "User | None":
        row = await db.fetchone("SELECT * FROM users WHERE id = ?", user_id)
        if not row:
            return None
        return cls(id=row["id"], name=row["name"], email=row["email"])
''',
]

CHAT_TURNS = [
    "User: Why does get_user return stale data after an update?",
    "Assistant: Likely the kv_store TTL — check invalidation on write.",
    "User: Where is kv_store defined?",
    "Assistant: See cache.py — it wraps an in-memory dict with TTL.",
]

BOILERPLATE_BLOCK = """
# Copyright 2024 Example Corp
# Licensed under MIT
# --- autogenerated ---
import sys
import logging
logging.basicConfig(level=logging.INFO)
""".strip().split("\n")


def generate_long_context(
    rng: random.Random,
    target_tokens: int = 800,
) -> Tuple[List[str], str]:
    """Build repo-scale context: files + chat + boilerplate."""
    lines: List[str] = []
    for _ in range(3):
        lines.extend(BOILERPLATE_BLOCK)
    for turn in CHAT_TURNS:
        lines.append(turn)
    repeats = 0
    while len(" ".join(lines).split()) < target_tokens and repeats < 8:
        for blob in SAMPLE_FILES:
            lines.extend(blob.strip().split("\n"))
            lines.append(f"# filler line {repeats} — padding context for KV pressure")
        repeats += 1
    questions = [
        "How does get_user interact with kv_store?",
        "What does User.fetch return when the row is missing?",
        "Explain normalize_path in helpers.",
    ]
    question = rng.choice(questions)
    return lines, question


@dataclass
class EvictionResult:
    """Outcome of applying a policy under budget B."""

    kept_indices: List[int]
    recall_oracle: float
    memory_used_ratio: float
    effective_context_multiplier: float


def evaluate_keep_set(
    records: List[TokenRecord],
    kept_indices: List[int],
    budget: int,
) -> EvictionResult:
    """Score how well kept tokens cover oracle-important set."""
    important_positions = {r.position for r in records if r.is_oracle_important}
    if not important_positions:
        recall = 1.0
    else:
        kept_set = set(kept_indices)
        recall = len(important_positions & kept_set) / len(important_positions)

    n = len(records)
    used_ratio = len(kept_indices) / max(n, 1)
    # Effective multiplier: recall achieved relative to uniform random at same budget
    random_expected = min(budget, n) / max(n, 1) * (
        len(important_positions) / max(n, 1)
    ) if n else 0
    if random_expected > 1e-6:
        multiplier = recall / random_expected
    else:
        multiplier = 1.0 if recall > 0 else 0.0

    return EvictionResult(
        kept_indices=sorted(kept_indices),
        recall_oracle=recall,
        memory_used_ratio=used_ratio,
        effective_context_multiplier=float(multiplier),
    )


def generate_dataset(
    n_samples: int,
    seed: int = 42,
) -> List[Tuple[List[TokenRecord], str]]:
    """Generate labeled contexts for training."""
    rng = random.Random(seed)
    np_rng = np.random.default_rng(seed)
    out = []
    for _ in range(n_samples):
        lines, question = generate_long_context(rng, target_tokens=600 + rng.randint(0, 400))
        records = build_token_records(lines, question, np_rng)
        out.append((records, question))
    return out
